#ifndef COMMANDS_H_
#define COMMANDS_H_

enum COMMAND {
    COMMAND_SET_FILE_NAME,
    COMMAND_OPEN_FILE,
    COMMAND_CLOSE_FILE,
    COMMAND_WRITE_BYTE,
    COMMAND_AUTO_ENCODE,
    COMMAND_METADATA_BYTE,
    COMMAND_LED_ON,
    COMMAND_LED_OFF
};

#endif